version: "3.9"
    
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    volumes:
      - ./db/:/var/www/db/
    environment:
      MYSQL_ROOT_PASSWORD: 12688ab
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 12688ab
    networks:
      - onlyoroscopo
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./site/:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 12688ab
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: onlyoroscopo.com
      LETSENCRYPT_HOST: onlyoroscopo.com
      LETSENCRYPT_EMAIL: l.lombardo@digitalhawks.it
      LETSENCRYPT_ENABLED: 1
    networks:
      - tier_1
      - onlyoroscopo

volumes:
  db_data: {}

networks:
  tier_1:
#    external:
#      name: network_tier_1
  onlyoroscopo:
 
